/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions/agentic_commerce/delegate_payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a delegated payment session
         * @description Tokenizes a credential for controlled usage by the merchant's PSP per the **Allowance** constraints.
         *     Exactly one credential type is currently supported: **card**.
         */
        post: operations["delegatePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DelegatePaymentRequest: {
            payment_method: components["schemas"]["PaymentMethodCard"];
            allowance: components["schemas"]["Allowance"];
            billing_address?: components["schemas"]["Address"];
            risk_signals: components["schemas"]["RiskSignal"][];
            metadata: {
                [key: string]: string;
            };
        };
        PaymentMethodCard: {
            /** @enum {string} */
            type: "card";
            /** @enum {string} */
            card_number_type: "fpan" | "network_token";
            /** @description network token or fallback fpan value */
            number: string;
            exp_month?: string;
            exp_year?: string;
            name?: string;
            cvc?: string;
            cryptogram?: string;
            eci_value?: string;
            checks_performed?: ("avs" | "cvv" | "ani" | "auth0")[];
            iin?: string;
            /** @enum {string} */
            display_card_funding_type: "credit" | "debit" | "prepaid";
            display_wallet_type?: string;
            display_brand?: string;
            display_last4?: string;
            metadata: {
                [key: string]: string;
            };
        };
        Address: {
            name: string;
            line_one: string;
            line_two?: string;
            city: string;
            state: string;
            /** @description ISO-3166-1 alpha-2 */
            country: string;
            postal_code: string;
        };
        Allowance: {
            /** @enum {string} */
            reason: "one_time";
            /** @description Minor units (e.g., $20 → 2000) */
            max_amount: number;
            /** @description ISO-4217 lowercase (e.g., usd) */
            currency: string;
            checkout_session_id: string;
            merchant_id: string;
            /** Format: date-time */
            expires_at: string;
        };
        RiskSignal: {
            /** @enum {string} */
            type: "card_testing";
            score: number;
            /** @enum {string} */
            action: "blocked" | "manual_review" | "authorized";
        };
        DelegatePaymentResponse: {
            /** @description Unique vault token identifier (vt_...) */
            id: string;
            /** Format: date-time */
            created: string;
            metadata: {
                [key: string]: string;
            };
        };
        Error: {
            /** @enum {string} */
            type: "invalid_request" | "rate_limit_exceeded" | "processing_error" | "service_unavailable";
            /** @enum {string} */
            code: "invalid_card" | "duplicate_request" | "idempotency_conflict";
            message: string;
            /** @description JSONPath of offending field */
            param?: string;
        };
    };
    responses: never;
    parameters: {
        Authorization: string;
        ContentType: string;
        AcceptLanguage: string;
        UserAgent: string;
        IdempotencyKey: string;
        RequestId: string;
        Signature: string;
        Timestamp: string;
        APIVersion: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    delegatePayment: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Content-Type": components["parameters"]["ContentType"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelegatePaymentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Echo of the request correlation ID */
                    "Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DelegatePaymentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Idempotency conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Semantic validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Processing error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
