/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/verifiedTokens/cardOnFile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verified Tokens cardOnFile Resource
         * @description Create a verified cardOnFile token by sending a request to cardOnFile resource. A cardOnFile verified token allows you to take payments that are made by the customer using a stored verified token, such as in one-click or in-app purchases.
         *
         *
         */
        post: operations["cardonfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifiedTokens/oneTime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verified Tokens oneTime Resource
         * @description Create a verified oneTime token by sending a request to oneTime resource. A oneTime verified token allows you to take payments that are made by the customer using a stored verified token, such as in one-click or in-app purchases.
         *
         *
         */
        post: operations["onetime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        card_plain: {
            /** @example card/plain */
            type: string;
            cardNumber: string;
            cardExpiryDate: {
                month: number;
                year: number;
            };
            cvc?: string;
            cardHolderName: components["schemas"]["verifiedTokens_cardOnFile_cardHolderName"];
            billingAddress?: components["schemas"]["verifiedTokens_cardOnFile_billingAddress"];
        };
        card_checkout: {
            /** @example card/checkout */
            type: string;
            /** @description Only session href of type verified token/card created in the same environment are accepted */
            sessionHref: string;
            cardHolderName: components["schemas"]["verifiedTokens_cardOnFile_cardHolderName"];
            billingAddress?: components["schemas"]["verifiedTokens_cardOnFile_billingAddress"];
        };
        /** @description An object that contains the card details or token location. */
        paymentInstrument: components["schemas"]["card_plain"] | components["schemas"]["card_checkout"];
        verifiedTokens_cardOnFile_request: {
            paymentInstrument: components["schemas"]["paymentInstrument"];
            merchant: {
                entity: string;
            };
            verificationCurrency: string;
            description?: string;
            /** Format: date-time */
            tokenExpiryDateTime?: string;
            namespace?: string;
            narrative?: {
                line1: string;
                line2?: string;
            };
        };
        verifiedTokens_oneTime_request: components["schemas"]["verifiedTokens_cardOnFile_request"];
        verifiedTokens_cardOnFile_billingAddress: {
            address1: string;
            address2?: string;
            address3?: string;
            postalCode: string;
            city: string;
            state?: string;
            countryCode: string;
        };
        verifiedTokens_cardOnFile_cardHolderName: string;
        verifiedTokens_cardOnFile_409_response: {
            _embedded: {
                verification: components["schemas"]["embedded_verification_cardOnFile_response"];
                token: components["schemas"]["embedded_tokens_conflicts_response"];
            };
        };
        verifiedTokens_cardOnFile_response: {
            _embedded: {
                verification: components["schemas"]["embedded_verification_cardOnFile_response"];
                token: components["schemas"]["embedded_tokens_response"];
            };
        };
        verifiedTokens_oneTime_200_response: {
            _embedded: {
                verification: components["schemas"]["embedded_verification_oneTime_response"];
                token: components["schemas"]["embedded_tokens_response"];
            };
        };
        verifiedTokens_oneTime_201_response: {
            _embedded: {
                verification: components["schemas"]["embedded_verification_oneTime_response"];
                token: {
                    /** @example 9902480679618049603 */
                    tokenId?: string;
                    /** @example Test Token Description */
                    description: string;
                    namespace?: string;
                    /**
                     * Format: date-time
                     * @example 2021-08-18T14:30:40Z
                     */
                    tokenExpiryDateTime: string;
                    tokenPaymentInstrument: {
                        /** @example card/tokenized */
                        type?: string;
                        /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0NzI0NE1rdUtjMUFJdjYxVnlibWZuUT0ifQ */
                        href?: string;
                    };
                    paymentInstrument: {
                        /** @example card/masked */
                        type?: string;
                        /** @example 4444********1111 */
                        cardNumber: string;
                        /** @example Sherlock Holmes */
                        cardHolderName: string;
                        cardExpiryDate: {
                            /**
                             * Format: int32
                             * @example 5
                             */
                            month: number;
                            /**
                             * Format: int32
                             * @example 2035
                             */
                            year: number;
                        };
                        billingAddress?: {
                            /** @example 221B Baker Street */
                            address1: string;
                            /** @example Marylebone */
                            address2?: string;
                            /** @example Westminster */
                            address3?: string;
                            /** @example NW1 6XE */
                            postalCode: string;
                            /** @example London */
                            city: string;
                            /** @example Greater London */
                            state?: string;
                            /** @example GB */
                            countryCode: string;
                        };
                        /** @example 444433 */
                        bin?: string;
                        /** @example VISA */
                        brand?: string;
                    };
                    _links: {
                        "tokens:token"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0NzI0NE1rdUtjMUFJdjYxVnlibWZuUT0ifQ */
                            href?: string;
                        };
                        "tokens:description"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0MWJVbkh1WTFGZExUNXJxc04va1ZoTFVzYW1OU1lxSFE2NHI1c2JkY1pWaSJ9 */
                            href?: string;
                        };
                        "tokens:cardHolderName"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdUpLN2N3VVc5WUk3czRUTW1RQ2JLdjFnVXlzakdPSXdWWkRhZkZyUmlMd3c9PSJ9 */
                            href?: string;
                        };
                        "tokens:cardExpiryDate"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdUpLN2N3VVc5WUk3czRUTW1RQ2JLdkVpVW5GNnBsZThNTXNQWTRGbzFzTXc9PSJ9 */
                            href?: string;
                        };
                        "tokens:billingAddress"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdFpSdXFxbWZlNVl1TkpHZEVvZXN3MTlCU0lmdCtxSTUyVDJSdXlmSTIwM3c9PSJ9 */
                            href?: string;
                        };
                        "tokens:schemeTransactionReference"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoiSENXWFZQZjNIZ1V3dnpDMElJZS9Zdmc4M0pYM3dDWEJTVnQrWVlacXdDUXFFKzhzaC8xNSs2d3NkTTdFWUFNVU9tdXBmUlZGeVNDY2dPMkhKV2NIcGc9PSJ9 */
                            href?: string;
                        };
                        "tokens:networkToken"?: {
                            /** @example https://try.access.worldpay.com/tokens/network */
                            href?: string;
                        };
                        curies?: {
                            /** @example https://try.access.worldpay.com/rels/tokens/{rel}.json */
                            href?: string;
                            /** @example tokens */
                            name?: string;
                            /** @example true */
                            templated?: boolean;
                        }[];
                    };
                };
            };
        };
        verifiedTokens_oneTime_206_response: {
            _embedded: {
                verification: components["schemas"]["embedded_verification_oneTime_response"];
                token: {
                    /** @example 9902480679618049603 */
                    tokenId?: string;
                    /** @example Test Token Description */
                    description: string;
                    namespace?: string;
                    /**
                     * Format: date-time
                     * @example 2021-08-18T14:30:40Z
                     */
                    tokenExpiryDateTime: string;
                    tokenPaymentInstrument: {
                        /** @example card/tokenized */
                        type?: string;
                        /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0NzI0NE1rdUtjMUFJdjYxVnlibWZuUT0ifQ */
                        href?: string;
                    };
                    paymentInstrument: {
                        /** @example card/masked */
                        type?: string;
                        /** @example 4444********1111 */
                        cardNumber: string;
                        /** @example Sherlock Holmes */
                        cardHolderName: string;
                        cardExpiryDate: {
                            /**
                             * Format: int32
                             * @example 5
                             */
                            month: number;
                            /**
                             * Format: int32
                             * @example 2035
                             */
                            year: number;
                        };
                        billingAddress?: {
                            /** @example 221B Baker Street */
                            address1: string;
                            /** @example Marylebone */
                            address2?: string;
                            /** @example Westminster */
                            address3?: string;
                            /** @example NW1 6XE */
                            postalCode: string;
                            /** @example London */
                            city: string;
                            /** @example Greater London */
                            state?: string;
                            /** @example GB */
                            countryCode: string;
                        };
                        /** @example 444433 */
                        bin?: string;
                        /** @example VISA */
                        brand?: string;
                    };
                    _links: {
                        "tokens:token"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0NzI0NE1rdUtjMUFJdjYxVnlibWZuUT0ifQ */
                            href?: string;
                        };
                        "tokens:description"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0MWJVbkh1WTFGZExUNXJxc04va1ZoTFVzYW1OU1lxSFE2NHI1c2JkY1pWaSJ9 */
                            href?: string;
                        };
                        "tokens:cardHolderName"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdUpLN2N3VVc5WUk3czRUTW1RQ2JLdjFnVXlzakdPSXdWWkRhZkZyUmlMd3c9PSJ9 */
                            href?: string;
                        };
                        "tokens:cardExpiryDate"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdUpLN2N3VVc5WUk3czRUTW1RQ2JLdkVpVW5GNnBsZThNTXNQWTRGbzFzTXc9PSJ9 */
                            href?: string;
                        };
                        "tokens:billingAddress"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdFpSdXFxbWZlNVl1TkpHZEVvZXN3MTlCU0lmdCtxSTUyVDJSdXlmSTIwM3c9PSJ9 */
                            href?: string;
                        };
                        "tokens:schemeTransactionReference"?: {
                            /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoiSENXWFZQZjNIZ1V3dnpDMElJZS9Zdmc4M0pYM3dDWEJTVnQrWVlacXdDUXFFKzhzaC8xNSs2d3NkTTdFWUFNVU9tdXBmUlZGeVNDY2dPMkhKV2NIcGc9PSJ9 */
                            href?: string;
                        };
                        "tokens:networkToken"?: {
                            /** @example https://try.access.worldpay.com/tokens/network */
                            href?: string;
                        };
                        curies?: {
                            /** @example https://try.access.worldpay.com/rels/tokens/{rel}.json */
                            href?: string;
                            /** @example tokens */
                            name?: string;
                            /** @example true */
                            templated?: boolean;
                        }[];
                    };
                };
            };
        };
        verifiedTokens_oneTime_409_response: {
            _embedded: {
                verification: components["schemas"]["embedded_verification_oneTime_response"];
                token: components["schemas"]["embedded_tokens_conflicts_response"];
            };
        };
        embedded_verification_cardOnFile_response: {
            /** @example verified */
            outcome: string;
            /** @example 000000000000020005060720116005060 */
            schemeTransactionReference?: string;
            /**
             * Format: date-time
             * @example 2024-01-26T17:11:46.226297Z
             */
            checkedAt: string;
            riskFactors?: {
                /** @example matched */
                risk: string;
                /** @example cvc */
                type: string;
            }[];
            paymentInstrument?: {
                /** @example card/plain */
                type: string;
                card?: {
                    number?: {
                        /**
                         * Format: date
                         * @example 4444
                         */
                        bin: string;
                        /**
                         * Format: date
                         * @example 1236
                         */
                        last4Digits: string;
                    };
                    /** @example GB */
                    countryCode?: string;
                    expiryDate?: {
                        /**
                         * Format: int32
                         * @example 1
                         */
                        month: number;
                        /**
                         * Format: int32
                         * @example 2024
                         */
                        year: number;
                    };
                    /** @example visa */
                    brand?: string;
                    /** @example credit */
                    fundingType?: string;
                    issuer?: {
                        /** @example UNKNOWN */
                        name: string;
                    };
                    /** @example Q1HJZ28RKA1EBL470G9XYG90R5D3E */
                    paymentAccountReference?: string;
                };
            };
            _links: {
                "verifications:verification"?: {
                    /** @example https://try.access.worldpay.com/verifications/accounts/Mjp1K3U0cTlvQWhPZFJxN2hQazYyaWx3PT06QUVTL0NCQy9QS0NTNVBhZGRpbmc6WjBXelE2YmQwNnlwTzRqbXk1bE9ERWZ3emlUbzMyZzlRNFE5a0NkRFV2ZlliWU5wS0FnOUpWcEJZUUIxTkp6Si9Kcy80UEVjUmlGbGcxeTE5SHhSVnJEV3JnUEtkYXk4dFVlYXF6ZDRoZ1k9 */
                    href?: string;
                };
                "payments:cardOnFileAuthorize"?: {
                    /** @example https://try.access.worldpay.com/payments/authorizations/cardOnFile/eyJrIjoia2FhYzM1ZiIsImxpbmtWZXJzaW9uIjoiMS4wLjAifQ==.rTSaWnvtqTfgLUF9d+yia:Xr:bMt7SfZl7sgZ0yFtqVrp79hk:hZjQ1rHNZUtukWvMHHnIhvkyp4QhRO0aAcDdOsiNkkSoq+It1ADfLty7k= */
                    href?: string;
                };
                "payments:recurringAuthorize"?: {
                    /** @example https://try.access.worldpay.com/payments/authorizations/recurring/eyJrIjoia2FhYzM1ZiIsImxpbmtWZXJzaW9uIjoiMS4wLjAifQ==.rTSaWnvtqTfgLUF9d+yia:Xr:bMt7SfZl7sgZ0yFtqVrp79hk:hZjQ1rHNZUtukWvMHHnIhvkyp4QhRO0aAcDdOsiNkkSoq+It1ADfLty7k= */
                    href?: string;
                };
                "payments:recurringSale"?: {
                    /** @example https://try.access.worldpay.com/payments/sales/recurring/eyJrIjoia2FhYzM1ZiIsImxpbmtWZXJzaW9uIjoiMS4wLjAifQ==.rTSaWnvtqTfgLUF9d+yia:Xr:bMt7SfZl7sgZ0yFtqVrp79hk:hZjQ1rHNZUtukWvMHHnIhvkyp4QhRO0aAcDdOsiNkkSoq+It1ADfLty7k= */
                    href?: string;
                };
                curies?: {
                    /** @example https://try.access.worldpay.com/rels/verifications/accounts/{rel} */
                    href?: string;
                    /** @example verifications */
                    name?: string;
                    /** @example true */
                    templated?: boolean;
                }[];
            };
        };
        embedded_verification_oneTime_response: {
            /** @example verified */
            outcome: string;
            /**
             * Format: date-time
             * @example 2024-01-26T17:11:46.226297Z
             */
            checkedAt: string;
            riskFactors?: {
                /** @example matched */
                risk: string;
                /** @example postcode */
                detail?: string;
                /** @example cvc */
                type: string;
            }[];
            paymentInstrument?: {
                /** @example card/plain */
                type: string;
                card?: {
                    number?: {
                        /**
                         * Format: date
                         * @example 4444
                         */
                        bin: string;
                        /**
                         * Format: date
                         * @example 1236
                         */
                        last4Digits: string;
                    };
                    /** @example GB */
                    countryCode?: string;
                    expiryDate?: {
                        /**
                         * Format: int32
                         * @example 1
                         */
                        month: number;
                        /**
                         * Format: int32
                         * @example 2024
                         */
                        year: number;
                    };
                    /** @example visa */
                    brand?: string;
                    /** @example credit */
                    fundingType?: string;
                    issuer?: {
                        /** @example UNKNOWN */
                        name: string;
                    };
                    /** @example Q1HJZ28RKA1EBL470G9XYG90R5D3E */
                    paymentAccountReference?: string;
                };
            };
            _links: {
                "verifications:verification": {
                    /** @example https://try.access.worldpay.com/verifications/accounts/Mjp1K3U0cTlvQWhPZFJxN2hQazYyaWx3PT06QUVTL0NCQy9QS0NTNVBhZGRpbmc6WjBXelE2YmQwNnlwTzRqbXk1bE9ERWZ3emlUbzMyZzlRNFE5a0NkRFV2ZlliWU5wS0FnOUpWcEJZUUIxTkp6Si9Kcy80UEVjUmlGbGcxeTE5SHhSVnJEV3JnUEtkYXk4dFVlYXF6ZDRoZ1k9 */
                    href: string;
                };
                curies: {
                    /** @example https://try.access.worldpay.com/rels/verifications/accounts/{rel} */
                    href: string;
                    /** @example verifications */
                    name: string;
                    /** @example true */
                    templated: boolean;
                }[];
            };
        };
        embedded_tokens_response: {
            /** @example 9902480679618049603 */
            tokenId?: string;
            /** @example Test Token Description */
            description: string;
            namespace?: string;
            /**
             * Format: date-time
             * @example 2021-08-18T14:30:40Z
             */
            tokenExpiryDateTime: string;
            /** @example 000000000000020005060720116005060 */
            schemeTransactionReference?: string;
            tokenPaymentInstrument: {
                /** @example card/tokenized */
                type?: string;
                /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0NzI0NE1rdUtjMUFJdjYxVnlibWZuUT0ifQ */
                href?: string;
            };
            paymentInstrument: {
                /** @example card/masked */
                type?: string;
                /** @example 4444********1111 */
                cardNumber: string;
                /** @example Sherlock Holmes */
                cardHolderName: string;
                cardExpiryDate: {
                    /**
                     * Format: int32
                     * @example 5
                     */
                    month: number;
                    /**
                     * Format: int32
                     * @example 2035
                     */
                    year: number;
                };
                billingAddress?: {
                    /** @example 221B Baker Street */
                    address1: string;
                    /** @example Marylebone */
                    address2?: string;
                    /** @example Westminster */
                    address3?: string;
                    /** @example NW1 6XE */
                    postalCode: string;
                    /** @example London */
                    city: string;
                    /** @example Greater London */
                    state?: string;
                    /** @example GB */
                    countryCode: string;
                };
                /** @example 444433 */
                bin?: string;
                /** @example VISA */
                brand?: string;
            };
            _links: {
                "tokens:token"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0NzI0NE1rdUtjMUFJdjYxVnlibWZuUT0ifQ */
                    href?: string;
                };
                "tokens:description"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0MWJVbkh1WTFGZExUNXJxc04va1ZoTFVzYW1OU1lxSFE2NHI1c2JkY1pWaSJ9 */
                    href?: string;
                };
                "tokens:cardHolderName"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdUpLN2N3VVc5WUk3czRUTW1RQ2JLdjFnVXlzakdPSXdWWkRhZkZyUmlMd3c9PSJ9 */
                    href?: string;
                };
                "tokens:cardExpiryDate"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdUpLN2N3VVc5WUk3czRUTW1RQ2JLdkVpVW5GNnBsZThNTXNQWTRGbzFzTXc9PSJ9 */
                    href?: string;
                };
                "tokens:billingAddress"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdFpSdXFxbWZlNVl1TkpHZEVvZXN3MTlCU0lmdCtxSTUyVDJSdXlmSTIwM3c9PSJ9 */
                    href?: string;
                };
                "tokens:schemeTransactionReference"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoiSENXWFZQZjNIZ1V3dnpDMElJZS9Zdmc4M0pYM3dDWEJTVnQrWVlacXdDUXFFKzhzaC8xNSs2d3NkTTdFWUFNVU9tdXBmUlZGeVNDY2dPMkhKV2NIcGc9PSJ9 */
                    href?: string;
                };
                "tokens:networkToken"?: {
                    /** @example https://try.access.worldpay.com/tokens/network */
                    href?: string;
                };
                curies?: {
                    /** @example https://try.access.worldpay.com/rels/tokens/{rel}.json */
                    href?: string;
                    /** @example tokens */
                    name?: string;
                    /** @example true */
                    templated?: boolean;
                }[];
            };
        };
        embedded_tokens_conflicts_response: {
            /** @example 9902480679618049603 */
            tokenId?: string;
            /** @example Test Token Description */
            description: string;
            namespace?: string;
            /**
             * Format: date-time
             * @example 2021-08-18T14:30:40Z
             */
            tokenExpiryDateTime: string;
            /** @example 000000000000020005060720116005060 */
            schemeTransactionReference?: string;
            tokenPaymentInstrument: {
                /** @example card/tokenized */
                type?: string;
                /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0NzI0NE1rdUtjMUFJdjYxVnlibWZuUT0ifQ */
                href?: string;
            };
            paymentInstrument: {
                /** @example card/masked */
                type?: string;
                /** @example 4444********1111 */
                cardNumber: string;
                /** @example Sherlock Holmes */
                cardHolderName: string;
                cardExpiryDate: {
                    /**
                     * Format: int32
                     * @example 5
                     */
                    month: number;
                    /**
                     * Format: int32
                     * @example 2035
                     */
                    year: number;
                };
                billingAddress?: {
                    /** @example 221B Baker Street */
                    address1: string;
                    /** @example Marylebone */
                    address2?: string;
                    /** @example Westminster */
                    address3?: string;
                    /** @example NW1 6XE */
                    postalCode: string;
                    /** @example London */
                    city: string;
                    /** @example Greater London */
                    state?: string;
                    /** @example GB */
                    countryCode: string;
                };
                /** @example 444433 */
                bin?: string;
                /** @example VISA */
                brand?: string;
            };
            conflicts?: {
                paymentInstrument?: {
                    /** @example Sherlock Holmes */
                    cardHolderName?: string;
                    cardExpiryDate?: {
                        /**
                         * Format: int32
                         * @example 5
                         */
                        month: number;
                        /**
                         * Format: int32
                         * @example 2035
                         */
                        year: number;
                    };
                    billingAddress?: {
                        /** @example 221B Baker Street */
                        address1: string;
                        /** @example Marylebone */
                        address2?: string;
                        /** @example Westminster */
                        address3?: string;
                        /** @example NW1 6XE */
                        postalCode: string;
                        /** @example London */
                        city: string;
                        /** @example Greater London */
                        state?: string;
                        /** @example GB */
                        countryCode: string;
                    };
                };
                schemeTransactionReference?: string;
            };
            _links: {
                "tokens:token"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0NzI0NE1rdUtjMUFJdjYxVnlibWZuUT0ifQ */
                    href?: string;
                };
                "tokens:description"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0MWJVbkh1WTFGZExUNXJxc04va1ZoTFVzYW1OU1lxSFE2NHI1c2JkY1pWaSJ9 */
                    href?: string;
                };
                "tokens:cardHolderName"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdUpLN2N3VVc5WUk3czRUTW1RQ2JLdjFnVXlzakdPSXdWWkRhZkZyUmlMd3c9PSJ9 */
                    href?: string;
                };
                "tokens:cardExpiryDate"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdUpLN2N3VVc5WUk3czRUTW1RQ2JLdkVpVW5GNnBsZThNTXNQWTRGbzFzTXc9PSJ9 */
                    href?: string;
                };
                "tokens:billingAddress"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoialRBL0FFelBzcnZpNCtzRGNRemh0d3ltd21ieGo3TlZLYzRYSkExOUhSdFpSdXFxbWZlNVl1TkpHZEVvZXN3MTlCU0lmdCtxSTUyVDJSdXlmSTIwM3c9PSJ9 */
                    href?: string;
                };
                "tokens:schemeTransactionReference"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoiSENXWFZQZjNIZ1V3dnpDMElJZS9Zdmc4M0pYM3dDWEJTVnQrWVlacXdDUXFFKzhzaC8xNSs2d3NkTTdFWUFNVU9tdXBmUlZGeVNDY2dPMkhKV2NIcGc9PSJ9 */
                    href?: string;
                };
                "tokens:conflicts"?: {
                    /** @example https://try.access.worldpay.com/tokens/eyJrIjoxLCJkIjoibjY5V0RxZUNzK3lkUXQ3aTVDYTdaNno4cHFtVWcrSlUvcU5wM1ViRE5QaGRlNDNXK1VNaWJ2UWxyRTZYcHpxUDFYcGRiTUhqbWEyMVdzdnljWU03aWRVcnY1WlVzZU1DditLZEExRGx6VUFiajNGVWpUbEVVOGN4QllnL0VoUC94bkptMVpCUERjdXYwd3JhMWdxb3FJcVI4Wjl5MW5CclRZcHFSRU5ndDIrMmNZTEFpZmJMakh0YW9taDRpNlRGaG1IK1BKZGc4UEpWNTVpV2MrbTB6UldEUmNZdHlrQ05MMTFqRnd0SEliRXlabkh2RndweEtteVBEZnk1bXgvdyJ9 */
                    href?: string;
                };
                "tokens:networkToken"?: {
                    /** @example https://try.access.worldpay.com/tokens/network */
                    href?: string;
                };
                curies?: {
                    /** @example https://try.access.worldpay.com/rels/tokens/{rel}.json */
                    href?: string;
                    /** @example tokens */
                    name?: string;
                    /** @example true */
                    templated?: boolean;
                }[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cardonfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_cardOnFile_request"];
            };
        };
        responses: {
            /** @description The payload has been verified and a matching Token already exists. This does not include token meta data, which still may be different */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_cardOnFile_response"];
                };
            };
            /** @description The payload has been verified and a Token has been created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_cardOnFile_response"];
                };
            };
            /** @description The supplied payload could not be verified. An unverified token has been created/matched. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_cardOnFile_response"];
                };
            };
            /** @description The payload has been verified but a Token exists that conflicts with some of the details in the request. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_cardOnFile_409_response"];
                };
            };
        };
    };
    onetime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_oneTime_request"];
            };
        };
        responses: {
            /** @description The payload has been verified and a matching Token already exists. This does not include token meta data, which still may be different */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_oneTime_200_response"];
                };
            };
            /** @description The payload has been verified and a Token has been created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_oneTime_201_response"];
                };
            };
            /** @description The supplied payload could not be verified. An unverified token has been created/matched. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_oneTime_206_response"];
                };
            };
            /** @description The payload has been verified but a Token exists that conflicts with some of the details in the request. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.worldpay.verified-tokens-v3.hal+json": components["schemas"]["verifiedTokens_oneTime_409_response"];
                };
            };
        };
    };
}
