import {z} from "zod";

export const hppSchema = z.object({
  amount: z.number(),
  currency: z.string().default("GBP"),
});

export const paymentSchema = z.object({
  cardHolderName: z.string(),
  sessionHref: z.string().describe("Optional Sessions url from Checkout SDK (provide either a sessionHref or tokenHref, never both)").optional(),
  tokenHref: z.string().describe("Token url from stored card (provide either a sessionHref or tokenHref, never both)").optional(),
  cvc: z.string().describe("Optional CVC (Provide a value in cvcSessionHref or cvc, never both.)").optional(),
  cvcSessionHref: z.string().describe("Optional CVC session url from Checkout SDK (Provide a value in cvcSessionHref or cvc, never both. Only supply if using tokenHref)").optional(),
  amount: z.number(),
  currency: z.string().default("GBP"),
  address1: z.string(),
  city: z.string(),
  postalCode: z.string().optional(),
  countryCode: z.string(),
  storeCard: z.boolean().default(false),
  createToken: z.boolean().default(false),
});


export const paymentDateQuerySchema = z.object({
  startDate: z
    .string()
    .optional()
    .describe(
      "Start date for the query in ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ)"
    ),
  endDate: z
    .string()
    .optional()
    .describe(
      "End date for the query in ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ)"
    ),
  pageSize: z.number().optional().default(20),
});

export const paymentTxnRefQuerySchema = z.object({
  transactionReference: z
    .string()
    .optional()
    .describe(
      "Transaction reference to filter payments by"
    ),
  pageSize: z.number().optional().default(20),
});

export const paymentIdQuerySchema = z.object({
  paymentId: z
    .string()
    .optional()
    .describe("Payment ID to filter payments by")
});

export const manageSchema = z.object({
  commandName: z.string(),
  commandHref: z.string(),
});


export const accountPayoutQuerySchema = z.object({
  narrative: z.string().optional().describe("Reference that may appear on beneficiary statements"),
  transactionReference: z.string().optional().describe("Unique reference for the payout"),
  accountNumber: z.string().optional().describe("Beneficiary bank account number"),
  payoutInstrumentId: z.string().optional().describe("A unique ID generated by Worldpay, holding the beneficiary bank details. You receive this in the response after successfully creating a payout instrument in the Parties API."),
  payoutInstrumentReference: z.string().optional().describe("A reference of the payoutInstrument created by you. This field holds the beneficiary bank details"),
  pageSize: z.number().max(499).default(20),
  countryCode: z.string().optional().describe("ISO 3166-1 Alpha-2 country code of the payout destination"),
  pageNumber: z.number().default(1),
  paymentState: z.enum(['AWAITING_EXECUTION', 'NEW', 'VALID', 'REJECTED','EXECUTED','COMPLETED','REVERSED','FAILED','INVALID']).optional(),
  startDate: z.string().optional().describe("Must be a Gregorian calendar date with ISO 8601 format YYYY-MM-DD"),
  endDate: z.string().optional().describe("Must be a Gregorian calendar date with ISO 8601 format YYYY-MM-DD"),
  payeeName: z.string().optional().describe("Complete payee name for the payout. This will be one of the following (depending on the beneficiary type): fullName - concatenated value from title + firstName + middleName + lastName; companyName"),
  sourceCurrency: z.string().optional().describe("Source ISO 4217 alpha-3 currency codes for the payout."),
  sourceAmount: z.number().optional().describe("Source amount. 18 digit precision including 2 decimal places"),
  targetCurrency: z.string().optional().describe("Target ISO 4217 alpha-3 currency codes for the payout."),
  targetAmount: z.number().optional().describe("18 digit precision including 2 decimal places"),
});
