openapi: 3.0.1
info:
  title: Payments API
  description: >
    Use a single API that orchestrates the payment flow to include FraudSight,
    3DS and Token creation.


    __Authentication__


    Set your headers 


    ```   

    Authorization: {your_credentials}    

    Content-Type: application/json    

    WP-Api-Version: 2024-06-01

    ```    


    Replace `{your_credentials}` with your base64-encoded Basic Auth username
    and password.  


    __DNS Whitelisting__


    Whitelist the following URLs:    

    * `https://try.access.worldpay.com/`

    * `https://access.worldpay.com/`


    Please ensure you use DNS whitelisting, not explicit IP whitelisting. When
    you make a request within Access Worldpay, you should always cache the
    response returned. 


    __API Collection__


    A full set of API examples based on different scenarios. 


    |&nbsp; | &nbsp; |

    |:----------------:|-------------|

    | <a href="/collections/access/payments/20240601/postman_collection.json"
    download="wp-payments-api-postman">Download Postman Collection </a>  |
    [Setup & environment config](./collections/index.md#instructions) |
  contact:
    name: Chamaeleon
  license:
    name: Worldpay
    url: developers.worldpay.com/license
  version: '2024-06-01'
  x-metadata:
    catalog-list: true
    business:
      - Enterprise
      - SMB
    generated: true
    tags:
      - Orchestration
    category:
      - 3DS & Exemptions
      - Card Payments
      - Risk Assessments
      - Tokens
      - Wallets
servers:
  - url: https://try.access.worldpay.com
    description: Try
  - url: https://access.worldpay.com
    description: Live
security:
  - BasicAuth: []
paths:
  /api/payments:
    $ref: paths/api_payments.yaml
  /api/payments/linkData/3dsDeviceData:
    $ref: paths/api_payments_linkData_3dsDeviceData.yaml
  /api/payments/linkData/3dsChallenges:
    $ref: paths/api_payments_linkData_3dsChallenges.yaml
  /api/payments/linkData/refunds:
    $ref: paths/api_payments_linkData_refunds.yaml
  /api/payments/linkData/partialRefunds:
    $ref: paths/api_payments_linkData_partialRefunds.yaml
  /api/payments/linkData/partialSettlements:
    $ref: paths/api_payments_linkData_partialSettlements.yaml
  /api/payments/linkData/cancellations:
    $ref: paths/api_payments_linkData_cancellations.yaml
  /api/payments/linkData/settlements:
    $ref: paths/api_payments_linkData_settlements.yaml
  /api/payments/linkData:
    $ref: paths/api_payments_linkData.yaml
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
